# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
#   schedule:
    # * is a special character in YAML so you have to quote this string
#     - cron:  '00 00 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      # Runs a single command using the runners shell
      - name: Install Dependency
        run: sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
          
      - name: Download LEDE Repo and Config
        run: |
          git clone https://github.com/coolsnowwolf/lede
          git clone https://github.com/jarieshan/AX6S-lede
      
      - name: Run any Script Step1
        working-directory: ./lede
        run: scripts/feeds update -a && scripts/feeds install -a
        
      - name: Run any Script Step2
        working-directory: ./lede
        run: scripts/feeds update -a && scripts/feeds install -a
        
      - name: Build Config
        working-directory: ./lede
        run : |
          make defconfig
          make oldconfig
          rm .config
          mv ../AX6S-lede/ax6s.config ./.config
        
      - name: Download Lib Step1
        working-directory: ./lede
        run: make -j8 download V=s
      - name: Download Lib Step2
        working-directory: ./lede
        run: make -j8 download V=s
      
      - name: Build AX6S Firmware
        working-directory: ./lede
        run: make -j$(($(nproc) + 1)) V=s
      
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: AX6S LEDE Firmware
          path: ./lede/bin/targets/
