# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
#   schedule:
    # * is a special character in YAML so you have to quote this string
#     - cron:  '00 00 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      # Runs a single command using the runners shell
      - name: Install Dependency
        run: sudo apt-get -y install build-essential ccache ecj fastjar file g++ python-pkg-resources gawk gettext git java-propose-classpath libelf-dev libncurses5-dev libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget python-distutils-extra python3-setuptools python3-dev rsync subversion swig time xsltproc zlib1g-dev
          
      - name: Download OpenWrt Repo and Config
        run: |
          git clone https://github.com/openwrt/openwrt.git
          git clone https://github.com/jarieshan/AX6S-lede
      
      - name: Run any Script Step1
        working-directory: ./openwrt
        run: scripts/feeds update -a && scripts/feeds install -a
        
      - name: Run any Script Step2
        working-directory: ./openwrt
        run: scripts/feeds update -a && scripts/feeds install -a
        
      - name: Build Config
        working-directory: ./openwrt
        run : |
          make defconfig
          make oldconfig
          rm .config
          mv ../AX6S-lede/ax6s.config ./.config
        
      - name: Download Lib Step1
        working-directory: ./openwrt
        run: make -j8 download V=s
      - name: Download Lib Step2
        working-directory: ./openwrt
        run: make -j8 download V=s
      
      - name: Build AX6S Firmware
        working-directory: ./openwrt
        run: make -j$(($(nproc) + 1)) V=s
      
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: AX6S OpenWrt Firmware
          path: ./openwrt/bin/targets/
